name: iOS CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest-large
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
    
    - name: Build
      run: |
        xcodebuild -scheme "Classdule" \
                   -destination "platform=iOS Simulator,name=iPhone 16,OS=18.6" \
                   build
    
    - name: Run tests
      run: |
        xcodebuild -scheme "Classdule" \
                   -destination "platform=iOS Simulator,name=iPhone 16,OS=18.6" \
                   test
