name: iOS CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    if: contains(github.event.head_commit.message, '[ci]') || github.event_name == 'pull_request'
    runs-on: macos-latest-large
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

    - name: Build and Test
      run: |
          xcodebuild -scheme "Classdule" -destination "platform=iOS Simulator,name=iPhone 16,OS=18.4" build
